In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from sklearn.datasets import load_breast_cancer

In [3]:
cancer = load_breast_cancer()

In [4]:
cancer.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [5]:
print(cancer['DESCR'])

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

:Number of Instances: 569

:Number of Attributes: 30 numeric, predictive attributes and the class

:Attribute Information:
    - radius (mean of distances from center to points on the perimeter)
    - texture (standard deviation of gray-scale values)
    - perimeter
    - area
    - smoothness (local variation in radius lengths)
    - compactness (perimeter^2 / area - 1.0)
    - concavity (severity of concave portions of the contour)
    - concave points (number of concave portions of the contour)
    - symmetry
    - fractal dimension ("coastline approximation" - 1)

    The mean, standard error, and "worst" or largest (mean of the three
    worst/largest values) of these features were computed for each image,
    resulting in 30 features.  For instance, field 0 is Mean Radius, field
    10 is Radius SE, field 20 is Worst Radius.

    - 

In [6]:
df = pd.DataFrame(data= cancer['data'], columns=cancer['feature_names'])

In [7]:
df.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
0                 0.07871  ...         25.38          17.33           184.60   
1                 0.05667  ...         24.99          23.41           158.80   
2                 0.05999  ...         23.57          25.53           152.50   
3                 0.09744  ...         14.91          26.50            98.87   
4                 0.05883  ...         22.54          16.67           152.20   

   worst area  worst smoothness  worst compactness  worst concavity  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   worst concave points  worst symmetry  worst fractal dimension  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 30 columns]

In [8]:
df['target'] = cancer['target']

In [9]:
df.drop('target', axis=1, inplace=True)

In [10]:
df.head(2)

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38           122.8     1001.0          0.11840   
1        20.57         17.77           132.9     1326.0          0.08474   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
0                 0.07871  ...         25.38          17.33            184.6   
1                 0.05667  ...         24.99          23.41            158.8   

   worst area  worst smoothness  worst compactness  worst concavity  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   

   worst concave points  worst symmetry  worst fractal dimension  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  

[2 rows x 30 columns]

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
from sklearn.svm import SVC 

In [13]:
X = df
y = cancer['target']

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [15]:
model = SVC()

In [16]:
model.fit(X_train, y_train)

SVC()

In [17]:
init_pred =  model.predict(X_test)

In [18]:
from sklearn.metrics import classification_report, confusion_matrix

In [19]:
print(classification_report(y_pred=init_pred, y_true=y_test))
print(confusion_matrix(y_pred=init_pred, y_true=y_test))

              precision    recall  f1-score   support

           0       0.98      0.88      0.93        67
           1       0.94      0.99      0.96       121

    accuracy                           0.95       188
   macro avg       0.96      0.94      0.95       188
weighted avg       0.95      0.95      0.95       188

[[ 59   8]
 [  1 120]]


In [20]:
from sklearn.model_selection import GridSearchCV

In [21]:
parameter = {
    'C': [1,2,3,111,10000,10,20,30, 0.1],
    'gamma': ['scale', 'auto']
    # 'gamma': [0.1,1, 0.001,0.0001,0.01]
}

In [22]:
grid = GridSearchCV(SVC(), param_grid=parameter, verbose=3)

In [23]:
grid.fit(X_train, y_train)

Fitting 5 folds for each of 18 candidates, totalling 90 fits
[CV 1/5] END ..................C=1, gamma=scale;, score=0.896 total time=   0.0s
[CV 2/5] END ..................C=1, gamma=scale;, score=0.908 total time=   0.0s
[CV 3/5] END ..................C=1, gamma=scale;, score=0.947 total time=   0.0s
[CV 4/5] END ..................C=1, gamma=scale;, score=0.855 total time=   0.0s
[CV 5/5] END ..................C=1, gamma=scale;, score=0.868 total time=   0.0s
[CV 1/5] END ...................C=1, gamma=auto;, score=0.623 total time=   0.0s
[CV 2/5] END ...................C=1, gamma=auto;, score=0.618 total time=   0.0s
[CV 3/5] END ...................C=1, gamma=auto;, score=0.618 total time=   0.0s
[CV 4/5] END ...................C=1, gamma=auto;, score=0.618 total time=   0.0s
[CV 5/5] END ...................C=1, gamma=auto;, score=0.618 total time=   0.0s
[CV 1/5] END ..................C=2, gamma=scale;, score=0.922 total time=   0.0s
[CV 2/5] END ..................C=2, gamma=scale;

GridSearchCV(estimator=SVC(),
             param_grid={'C': [1, 2, 3, 111, 10000, 10, 20, 30, 0.1],
                         'gamma': ['scale', 'auto']},
             verbose=3)

In [24]:
grid.best_params_

{'C': 10000, 'gamma': 'scale'}

In [25]:
grid_prediction = grid.predict(X_test)

In [26]:
print(confusion_matrix(y_pred=grid_prediction, y_true=y_test))
print(classification_report(y_pred=grid_prediction, y_true=y_test))

[[ 63   4]
 [  2 119]]
              precision    recall  f1-score   support

           0       0.97      0.94      0.95        67
           1       0.97      0.98      0.98       121

    accuracy                           0.97       188
   macro avg       0.97      0.96      0.96       188
weighted avg       0.97      0.97      0.97       188



In [27]:
print(classification_report(y_pred=init_pred, y_true=y_test))
print(confusion_matrix(y_pred=init_pred, y_true=y_test))

              precision    recall  f1-score   support

           0       0.98      0.88      0.93        67
           1       0.94      0.99      0.96       121

    accuracy                           0.95       188
   macro avg       0.96      0.94      0.95       188
weighted avg       0.95      0.95      0.95       188

[[ 59   8]
 [  1 120]]
